# 17. 프로미스

> References <br> <a href="http://www.yes24.com/Product/Goods/92742567?OzSrank=1">모던 자바스크립트 Deep Dive</a> _.이웅모_

## 1. 콜백 패턴의 단점

1. **콜백 지옥**

- 비동기 동작에 대한 후속 처리는 **콜백 함수**를 사용하게 된다.
- 연속 된 비동기 처리에 의해 비동기 처리에 대한 **후속 처리가 중첩**되어 복잡도가 높아지는 현상을 **콜백 지옥**이라고 한다.

2. **예외 처리의 한계**

- 비동기 처리에 에러가 발생할 경우, try-catch 문법을 통해 **에러를 캐치할 수 없다.**
- 예외 처리를 위해서는 콜백함수마다 예외 처리를 해주어야 한다.

```javascript
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error("캐치한 에러", e);
}
```

## 2. 프로미스 기본 개념

```javascript
// GET 요청을 위한 비동기 함수
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet("https://jsonplaceholder.typicode.com/posts/1");
```

- **프로미스**는 콜백 지옥과 에러 처리가 힘든 콜백 패턴의 단점을 해결하기 위해 ES6에서 도입되었다.
- 프로미스 생성자 함수는 **resolve 함수**와 **reject 함수**에 해당하는 인수와 함께 **비동기 처리를 수행할 콜백 함수**를 전달받는다.

- **프로미스 상태**
  - **pending** : 비동기 처리가 수행되지 않은 상태
  - **fulfiled** : 비동기 처리 성공 ➡ **resolve 함수** 호출
  - **rejected** : 비동기 처리 실패 ➡ **reject 함수** 호출

## 3. 프로미스 체이닝

```javascript
const url = "https://jsonplaceholder.typicode.com/posts/1";

promiseGet(url)
  .then((data) => {
    return promiseGet(data);
  })
  .then((data) => {
    return promiseGet(data);
  })
  .then((data) => {
    console.log(data);
  })
  .catch((err) => {
    console.log(err);
  });
```

- **프로세스 체인**은 **후속 처리 메소드**를 연속으로 호출하는 것을 말한다.
- 후속 처리 메소드는 **then/catch/finally**가 있다.

- then

  - **두 개의 콜백함수**를 인수로 전달받는다.
  - 첫 번째 콜백함수는 **fulfiled** 상태에서 호출되며, 두 번째 콜백함수는 **rejected** 상태에서 호출된다.

- catch

  - **한 개의 콜백 함수**를 인수로 전달 받는다.
  - then의 두 번째 콜백함수로 에러를 처리하는 방법보다 더욱 선호된다. <br>
    👉 then의 두 번째 콜백함수로 에러를 처리할 경우 첫 번째 콜백함수에서 에러 발생 시 처리를 하지 않기 때문이다.

- finally
  - fulfiled와 rejected에 상관없이 **무조건 한 번 호출된다.**

## 4. async/await

```javascript
const asyncGet = async () => {
  const url = "https://jsonplaceholder.typicode.com/posts/1";
  try {
    const data1 = await promiseGet(url);
    const data2 = await promiseGet(data1);
    console.log(data);
  } catch (err) {
    console.log(err);
  }
};

asyncGet();
```

- ES8부터 도입 된 비동기 패턴이다.
- **동기 처리를 하듯** 코드를 작성하여 가독성을 높일 수 있다.
- async/await 패턴에서 에러 처리가 어려운 이유
  - 다양한 에러 조건에 대해 프로미스의 catch 메소드의 경우 유연한 처리가 가능하지만, async/await의 경우 try-catch문을 중첩하는 등의 조치가 필요하다.
  - 데이터를 받을 변수에 에러가 담겨 사용자에게 에러를 노출시킬 수 있다.
